# Generated by Django 5.2.6 on 2025-11-07 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingimage',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
