# Generated by Django 5.2.6 on 2025-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parkingimage_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingimage',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
