# Generated by Django 5.2.6 on 2025-11-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_parkingimage_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingapprovalrequest',
            name='horario_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingapprovalrequest',
            name='horario_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingapprovalrequest',
            name='nivel_seguridad',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Estándar', 'Estándar'), ('Premium', 'Premium'), ('Alto', 'Alto')], default='Estándar', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='nivel_seguridad',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Estándar', 'Estándar'), ('Premium', 'Premium'), ('Alto', 'Alto')], default='Estándar', max_length=20),
        ),
    ]
