# Generated by Django 5.2.7 on 2025-11-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_alter_parkingapprovalrequest_horario_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
