# Generated by Django 5.2.6 on 2025-11-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_eliminado_user_fecha_eliminacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador General'), ('owner', 'Dueño de Estacionamiento'), ('client', 'Cliente')], default='client', max_length=10),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
