# Generated by Django 5.2.6 on 2025-11-09 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_parkingimage_creado_en'),
        ('reservations', '0001_initial'),
        ('users', '0003_alter_car_options_alter_user_options_alter_user_rol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='tipo_reserva',
            field=models.CharField(choices=[('hora', 'Por Hora'), ('dia', 'Por Día'), ('mes', 'Por Mes')], default='hora', max_length=10),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['estado', 'hora_entrada'], name='reservation_estado_3797f2_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['usuario', 'estado'], name='reservation_usuario_a95162_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['estacionamiento', 'hora_entrada'], name='reservation_estacio_4d9d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['codigo_reserva'], name='reservation_codigo__1b3384_idx'),
        ),
    ]
