# Generated by Django 5.2.4 on 2025-12-03 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_alter_reservation_options_reservation_tipo_reserva_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_ticket', models.CharField(blank=True, max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('reserva', 'Reserva'), ('pago_validado', 'Pago Validado por Owner'), ('manual', 'Manual')], default='reserva', max_length=20)),
                ('estado', models.CharField(choices=[('valido', 'Válido'), ('usado', 'Usado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/')),
                ('qr_data', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_validez_desde', models.DateTimeField(blank=True, null=True)),
                ('fecha_validez_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('intentos_validacion', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='reservations.reservation')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('validado', 'Validado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado'), ('error_validacion', 'Error Validación')], max_length=20)),
                ('detalles', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Ticket',
                'verbose_name_plural': 'Historial de Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['codigo_ticket'], name='tickets_tic_codigo__7fedda_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'fecha_emision'], name='tickets_tic_estado_565788_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reserva'], name='tickets_tic_reserva_49db8d_idx'),
        ),
    ]
